const copy = {
  en: {
    label: "English", nav: ["Home", "Support", "Privacy"],
    land: ["Make your moments move.", "Turn videos and Live Photos into animated cutouts, then compose them into layered scenes with text, effects, and sound.", "For iOS 17 or later", "Create cutouts", "Extract people from selected videos and Live Photos right on your device.", "Compose a scene", "Layer multiple elements and adjust their position, size, rotation, and timing. Add backgrounds, frames, stickers, and text.", "Add sound and export", "Place extracted audio on a timeline, then export as GIF, transparent HEVC video, or H.264 video.", "Your media stays on your device. GIFBloom does not upload your photos or videos."],
    support: ["Get help with GIFBloom", "Find answers about importing media, creating cutouts, editing, and exporting.", "Frequently asked questions", ["Which media can I use?", "Choose a video, Live Photo, or photo from your library. GIFBloom uses the media you select for your project."], ["Why can't GIFBloom create a cutout?", "Person cutout uses iOS 17 or later. Try a clear image or video with a visible person, and make sure the source media has finished loading."], ["Which export format should I choose?", "Choose GIF for easy sharing, HEVC with alpha when you need transparency, or H.264 for broad video compatibility. Available options depend on your project and device."], ["Where are my projects and exports saved?", "Projects are saved in GIFBloom on your device. When you export, choose whether to save the result to Photos or share it using the iOS share sheet."], "Contact", "For help or to report a problem, email us at"],
    privacy: ["GIFBloom processes your selected media on your device. We do not collect personal information through the app or upload your photos and videos to our servers.", ["Information we collect", "GIFBloom does not ask you to create an account and does not collect personal information, usage analytics, or advertising identifiers."], ["Media processing", "Photos, videos, audio, and project content you select are processed on your device. GIFBloom does not send this content to developer-operated servers. If you use iOS Photos, iCloud, or the system share sheet, Apple's or the chosen service's own terms and privacy practices apply."], ["Local storage and exports", "Projects are stored locally in the app. You choose when to export a result to Photos or share it with another app. Removing GIFBloom may delete projects stored only on the device; keep separate copies of anything you want to retain."], ["Permissions", "GIFBloom uses the media you choose through iOS selection interfaces. iOS may ask for Photos access when you save an export to your library. You can manage permissions in iOS Settings."], ["Children, changes, and contact", "GIFBloom is not designed to collect personal information from children. We may update this policy when the app changes. For privacy questions, contact"]]
  },
  "zh-Hans": {
    label: "简体中文", nav: ["首页", "支持", "隐私政策"],
    land: ["让每个瞬间动起来。", "将视频和 Live Photo 变成动态剪影，再加入文字、特效和声音，合成多层场景。", "需要 iOS 17 或更高版本", "生成剪影", "在设备本地从所选视频和 Live Photo 中提取人物。", "合成场景", "叠加多个元素，调整位置、大小、旋转和出现时间。添加背景、画框、贴纸和文字。", "添加声音并导出", "将提取的音频放入时间轴，导出为 GIF、透明 HEVC 视频或 H.264 视频。", "素材保留在你的设备上。GIFBloom 不会上传你的照片或视频。"],
    support: ["GIFBloom 使用帮助", "查看有关导入素材、生成剪影、编辑和导出的解答。", "常见问题", ["可以使用哪些素材？", "你可以从图库中选择视频、Live Photo 或照片。GIFBloom 只会使用你为工程选择的素材。"], ["为什么无法生成剪影？", "人物剪影功能需要 iOS 17 或更高版本。请尝试人物清晰可见的照片或视频，并确认素材已加载完成。"], ["应该选择哪种导出格式？", "便于分享可选 GIF；需要透明效果可选带 Alpha 通道的 HEVC；需要更广泛的视频兼容性可选 H.264。可用选项取决于工程和设备。"], ["工程和导出文件保存在哪里？", "工程保存在设备上的 GIFBloom 中。导出时，你可以选择存入“照片”，或通过 iOS 分享菜单发送到其他 App。"], "联系我们", "如需帮助或反馈问题，请发送邮件至"],
    privacy: ["GIFBloom 在你的设备上处理所选素材。我们不会通过 App 收集个人信息，也不会将你的照片或视频上传到我们的服务器。", ["我们收集的信息", "GIFBloom 不要求创建账号，也不收集个人信息、使用分析数据或广告标识符。"], ["素材处理", "你选择的照片、视频、音频和工程内容均在设备上处理。GIFBloom 不会将这些内容发送到开发者运营的服务器。如果你使用 iOS“照片”、iCloud 或系统分享菜单，则适用 Apple 或你选择的服务自身的条款和隐私规则。"], ["本地存储与导出", "工程保存在 App 本地。你可以自行选择何时将作品导出到“照片”或分享给其他 App。移除 GIFBloom 可能会删除仅保存在设备上的工程；请为需要保留的内容另存副本。"], ["权限", "GIFBloom 通过 iOS 选择界面使用你主动选择的素材。将作品存入图库时，iOS 可能会请求“照片”访问权限。你可以在 iOS 设置中管理权限。"], ["儿童、政策更新与联系", "GIFBloom 不以收集儿童个人信息为目的。App 功能变化时，我们可能会更新本政策。如有隐私问题，请联系"]]
  },
  "zh-Hant": {
    label: "繁體中文", nav: ["首頁", "支援", "隱私政策"],
    land: ["讓每個瞬間動起來。", "將影片和 Live Photo 變成動態剪影，再加入文字、特效和聲音，合成多層場景。", "需要 iOS 17 或以上版本", "產生剪影", "在裝置本機從所選影片和 Live Photo 中擷取人物。", "合成場景", "疊加多個元素，調整位置、大小、旋轉和出現時間。加入背景、相框、貼圖和文字。", "加入聲音並匯出", "將擷取的音訊放入時間軸，匯出為 GIF、透明 HEVC 影片或 H.264 影片。", "素材保留在你的裝置上。GIFBloom 不會上傳你的照片或影片。"],
    support: ["GIFBloom 使用說明", "查看匯入素材、產生剪影、編輯和匯出的常見解答。", "常見問題", ["可以使用哪些素材？", "你可以從圖庫選擇影片、Live Photo 或照片。GIFBloom 只會使用你為專案選擇的素材。"], ["為什麼無法產生剪影？", "人物剪影功能需要 iOS 17 或以上版本。請嘗試人物清晰可見的照片或影片，並確認素材已載入完成。"], ["應該選擇哪種匯出格式？", "方便分享可選 GIF；需要透明效果可選帶有 Alpha 通道的 HEVC；需要較廣泛的影片相容性可選 H.264。可用選項取決於專案和裝置。"], ["專案和匯出檔案儲存在哪裡？", "專案儲存在裝置上的 GIFBloom 中。匯出時，你可以選擇存入「照片」，或透過 iOS 分享選單傳送到其他 App。"], "聯絡我們", "如需協助或回報問題，請寄送電子郵件至"],
    privacy: ["GIFBloom 在你的裝置上處理所選素材。我們不會透過 App 收集個人資訊，也不會將你的照片或影片上傳至我們的伺服器。", ["我們收集的資訊", "GIFBloom 不要求建立帳號，也不會收集個人資訊、使用分析資料或廣告識別碼。"], ["素材處理", "你選擇的照片、影片、音訊和專案內容均在裝置上處理。GIFBloom 不會將這些內容傳送至開發者營運的伺服器。如果你使用 iOS「照片」、iCloud 或系統分享選單，則適用 Apple 或你所選服務本身的條款和隱私規則。"], ["本機儲存與匯出", "專案儲存在 App 本機。你可以自行選擇何時將作品匯出至「照片」或分享給其他 App。移除 GIFBloom 可能會刪除僅儲存在裝置上的專案；請為需要保留的內容另存副本。"], ["權限", "GIFBloom 透過 iOS 選擇介面使用你主動選擇的素材。將作品存入圖庫時，iOS 可能會要求「照片」存取權限。你可以在 iOS 設定中管理權限。"], ["兒童、政策更新與聯絡", "GIFBloom 並非以收集兒童個人資訊為目的。App 功能變更時，我們可能會更新本政策。如有隱私問題，請聯絡"]]
  },
  de: {
    label: "Deutsch", nav: ["Start", "Support", "Datenschutz"],
    land: ["Mach deine Momente lebendig.", "Verwandle Videos und Live Photos in animierte Freisteller und gestalte daraus mehrschichtige Szenen mit Text, Effekten und Ton.", "Für iOS 17 oder neuer", "Freisteller erstellen", "Stelle Personen direkt auf deinem Gerät aus ausgewählten Videos und Live Photos frei.", "Szene gestalten", "Kombiniere mehrere Elemente und passe Position, Größe, Drehung und Timing an. Ergänze Hintergründe, Rahmen, Sticker und Text.", "Ton hinzufügen und exportieren", "Lege extrahiertes Audio auf eine Zeitleiste und exportiere als GIF, transparentes HEVC- oder H.264-Video.", "Deine Medien bleiben auf deinem Gerät. GIFBloom lädt deine Fotos und Videos nicht hoch."],
    support: ["Hilfe zu GIFBloom", "Antworten zum Importieren, Freistellen, Bearbeiten und Exportieren.", "Häufige Fragen", ["Welche Medien kann ich verwenden?", "Wähle ein Video, Live Photo oder Foto aus deiner Mediathek. GIFBloom verwendet die Medien, die du für dein Projekt auswählst."], ["Warum kann GIFBloom keine Person freistellen?", "Die Personenfreistellung erfordert iOS 17 oder neuer. Versuche es mit einem klaren Bild oder Video mit sichtbarer Person und warte, bis die Quelldatei geladen ist."], ["Welches Exportformat soll ich wählen?", "GIF eignet sich zum einfachen Teilen, HEVC mit Alpha für Transparenz und H.264 für breite Videokompatibilität. Die verfügbaren Optionen hängen von Projekt und Gerät ab."], ["Wo werden Projekte und Exporte gespeichert?", "Projekte werden lokal in GIFBloom gespeichert. Beim Export kannst du das Ergebnis in Fotos sichern oder über das iOS-Teilen-Menü an eine andere App senden."], "Kontakt", "Bei Fragen oder Problemen schreib uns an"],
    privacy: ["GIFBloom verarbeitet ausgewählte Medien auf deinem Gerät. Wir erheben über die App keine personenbezogenen Daten und laden deine Fotos oder Videos nicht auf unsere Server hoch.", ["Erhobene Informationen", "GIFBloom verlangt kein Konto und erhebt keine personenbezogenen Daten, Nutzungsanalysen oder Werbekennungen."], ["Medienverarbeitung", "Ausgewählte Fotos, Videos, Audiodateien und Projektinhalte werden auf deinem Gerät verarbeitet. GIFBloom sendet diese Inhalte nicht an vom Entwickler betriebene Server. Wenn du iOS Fotos, iCloud oder das Teilen-Menü verwendest, gelten die Datenschutzbestimmungen von Apple beziehungsweise des gewählten Dienstes."], ["Lokale Speicherung und Export", "Projekte werden lokal in der App gespeichert. Du entscheidest, wann du ein Ergebnis in Fotos speicherst oder mit einer anderen App teilst. Beim Entfernen von GIFBloom können ausschließlich auf dem Gerät gespeicherte Projekte gelöscht werden. Sichere Inhalte, die du behalten möchtest."], ["Berechtigungen", "GIFBloom verwendet Medien, die du über die iOS-Auswahlfunktionen auswählst. Beim Speichern eines Exports in deiner Mediathek kann iOS nach Fotos-Zugriff fragen. Berechtigungen kannst du in den iOS-Einstellungen verwalten."], ["Kinder, Änderungen und Kontakt", "GIFBloom ist nicht darauf ausgelegt, personenbezogene Daten von Kindern zu erfassen. Bei Änderungen an der App können wir diese Richtlinie aktualisieren. Bei Fragen zum Datenschutz kontaktiere"]]
  },
  es: {
    label: "Español", nav: ["Inicio", "Soporte", "Privacidad"],
    land: ["Dale movimiento a tus momentos.", "Convierte vídeos y Live Photos en recortes animados y crea escenas por capas con texto, efectos y sonido.", "Para iOS 17 o posterior", "Crea recortes", "Extrae personas de vídeos y Live Photos seleccionados directamente en tu dispositivo.", "Compón una escena", "Combina varias capas y ajusta su posición, tamaño, giro y duración. Añade fondos, marcos, stickers y texto.", "Añade sonido y exporta", "Coloca el audio extraído en una línea de tiempo y exporta como GIF, vídeo HEVC transparente o vídeo H.264.", "Tus archivos permanecen en tu dispositivo. GIFBloom no sube tus fotos ni vídeos."],
    support: ["Ayuda de GIFBloom", "Respuestas sobre cómo importar contenido, crear recortes, editar y exportar.", "Preguntas frecuentes", ["¿Qué contenido puedo usar?", "Elige un vídeo, Live Photo o una foto de tu biblioteca. GIFBloom utiliza el contenido que seleccionas para tu proyecto."], ["¿Por qué GIFBloom no puede crear un recorte?", "La extracción de personas requiere iOS 17 o posterior. Prueba con una imagen o vídeo nítido donde se vea a una persona y espera a que termine de cargarse el archivo."], ["¿Qué formato de exportación debo elegir?", "Elige GIF para compartir fácilmente, HEVC con alpha si necesitas transparencia o H.264 para una amplia compatibilidad de vídeo. Las opciones dependen del proyecto y del dispositivo."], ["¿Dónde se guardan mis proyectos y exportaciones?", "Los proyectos se guardan localmente en GIFBloom. Al exportar, puedes guardar el resultado en Fotos o compartirlo con otra app mediante la hoja de compartir de iOS."], "Contacto", "Si necesitas ayuda o quieres informar de un problema, escríbenos a"],
    privacy: ["GIFBloom procesa el contenido que seleccionas en tu dispositivo. No recopilamos información personal mediante la app ni subimos tus fotos o vídeos a nuestros servidores.", ["Información que recopilamos", "GIFBloom no requiere una cuenta y no recopila información personal, datos de uso ni identificadores publicitarios."], ["Procesamiento de contenido", "Las fotos, vídeos, audios y proyectos que seleccionas se procesan en tu dispositivo. GIFBloom no envía este contenido a servidores gestionados por el desarrollador. Si usas Fotos de iOS, iCloud o la hoja de compartir del sistema, se aplican las condiciones y prácticas de privacidad de Apple o del servicio elegido."], ["Almacenamiento local y exportaciones", "Los proyectos se guardan localmente en la app. Tú decides cuándo exportar un resultado a Fotos o compartirlo con otra app. Al eliminar GIFBloom, podrían borrarse los proyectos guardados solo en el dispositivo; conserva copias de lo que quieras mantener."], ["Permisos", "GIFBloom usa el contenido que eliges mediante las interfaces de selección de iOS. iOS puede solicitar acceso a Fotos cuando guardes una exportación en tu biblioteca. Puedes gestionar los permisos en Ajustes de iOS."], ["Menores, cambios y contacto", "GIFBloom no está diseñada para recopilar información personal de menores. Esta política puede actualizarse si cambia la app. Si tienes preguntas sobre privacidad, contacta con"]]
  },
  fr: {
    label: "Français", nav: ["Accueil", "Assistance", "Confidentialité"],
    land: ["Donnez vie à vos instants.", "Transformez des vidéos et des Live Photos en détourages animés, puis composez des scènes en calques avec texte, effets et son.", "iOS 17 ou version ultérieure", "Détourez des personnes", "Détourez des personnes dans les vidéos et Live Photos sélectionnées, directement sur votre appareil.", "Composez une scène", "Superposez plusieurs éléments et réglez leur position, taille, rotation et durée. Ajoutez des arrière-plans, cadres, autocollants et du texte.", "Ajoutez du son et exportez", "Placez l’audio extrait sur une timeline, puis exportez en GIF, vidéo HEVC transparente ou vidéo H.264.", "Vos médias restent sur votre appareil. GIFBloom ne téléverse pas vos photos ni vos vidéos."],
    support: ["Aide GIFBloom", "Réponses sur l’importation, le détourage, la modification et l’exportation.", "Questions fréquentes", ["Quels médias puis-je utiliser ?", "Choisissez une vidéo, une Live Photo ou une photo de votre photothèque. GIFBloom utilise les médias que vous sélectionnez pour votre projet."], ["Pourquoi GIFBloom ne peut-il pas détourer une personne ?", "Le détourage de personnes nécessite iOS 17 ou une version ultérieure. Essayez avec une image ou une vidéo nette où la personne est visible, et attendez la fin du chargement du média."], ["Quel format d’exportation choisir ?", "Choisissez le GIF pour partager facilement, HEVC avec alpha pour conserver la transparence, ou H.264 pour une large compatibilité vidéo. Les options dépendent du projet et de l’appareil."], ["Où sont enregistrés mes projets et mes exports ?", "Les projets sont enregistrés localement dans GIFBloom. Lors de l’exportation, choisissez d’enregistrer le résultat dans Photos ou de le partager avec une autre app via la feuille de partage iOS."], "Contact", "Pour obtenir de l’aide ou signaler un problème, écrivez-nous à"],
    privacy: ["GIFBloom traite les médias que vous sélectionnez sur votre appareil. Nous ne collectons pas de données personnelles par l’intermédiaire de l’app et ne téléversons pas vos photos ou vidéos sur nos serveurs.", ["Informations collectées", "GIFBloom ne nécessite aucun compte et ne collecte aucune donnée personnelle, statistique d’utilisation ou identifiant publicitaire."], ["Traitement des médias", "Les photos, vidéos, fichiers audio et projets sélectionnés sont traités sur votre appareil. GIFBloom ne transmet pas ces contenus à des serveurs exploités par le développeur. Si vous utilisez Photos, iCloud ou la feuille de partage d’iOS, les règles de confidentialité d’Apple ou du service choisi s’appliquent."], ["Stockage local et exportations", "Les projets sont stockés localement dans l’app. Vous choisissez quand exporter un résultat vers Photos ou le partager avec une autre app. La suppression de GIFBloom peut effacer les projets stockés uniquement sur l’appareil ; conservez une copie de ce que vous souhaitez garder."], ["Autorisations", "GIFBloom utilise les médias que vous choisissez via les interfaces de sélection d’iOS. iOS peut demander l’accès à Photos lorsque vous enregistrez un export dans votre photothèque. Gérez les autorisations dans Réglages iOS."], ["Enfants, mises à jour et contact", "GIFBloom n’est pas conçue pour collecter des données personnelles sur les enfants. Nous pouvons mettre à jour cette politique si l’app évolue. Pour toute question sur la confidentialité, contactez"]]
  },
  it: {
    label: "Italiano", nav: ["Home", "Supporto", "Privacy"],
    land: ["Dai movimento ai tuoi momenti.", "Trasforma video e Live Photo in ritagli animati e componi scene a livelli con testo, effetti e audio.", "Per iOS 17 o versioni successive", "Crea ritagli", "Ritaglia le persone dai video e dalle Live Photo selezionate direttamente sul dispositivo.", "Componi una scena", "Sovrapponi più elementi e regola posizione, dimensioni, rotazione e durata. Aggiungi sfondi, cornici, adesivi e testo.", "Aggiungi audio ed esporta", "Disponi l’audio estratto sulla timeline ed esporta come GIF, video HEVC trasparente o video H.264.", "I tuoi contenuti restano sul dispositivo. GIFBloom non carica foto o video."],
    support: ["Assistenza GIFBloom", "Risposte su importazione, ritaglio, modifica ed esportazione.", "Domande frequenti", ["Quali contenuti posso usare?", "Scegli un video, una Live Photo o una foto dalla libreria. GIFBloom usa i contenuti che selezioni per il progetto."], ["Perché GIFBloom non riesce a creare un ritaglio?", "Il ritaglio delle persone richiede iOS 17 o versioni successive. Prova con un’immagine o un video nitido in cui la persona sia visibile e attendi il caricamento del file."], ["Quale formato di esportazione devo scegliere?", "Scegli GIF per condividere facilmente, HEVC con alpha per mantenere la trasparenza o H.264 per un’ampia compatibilità video. Le opzioni dipendono dal progetto e dal dispositivo."], ["Dove vengono salvati i progetti e le esportazioni?", "I progetti vengono salvati localmente in GIFBloom. Durante l’esportazione puoi salvare il risultato in Foto o condividerlo con un’altra app tramite il pannello di condivisione di iOS."], "Contatti", "Per ricevere assistenza o segnalare un problema, scrivici a"],
    privacy: ["GIFBloom elabora i contenuti selezionati sul dispositivo. Non raccogliamo dati personali tramite l’app e non carichiamo foto o video sui nostri server.", ["Informazioni raccolte", "GIFBloom non richiede un account e non raccoglie dati personali, analisi di utilizzo o identificativi pubblicitari."], ["Elaborazione dei contenuti", "Foto, video, audio e progetti selezionati vengono elaborati sul dispositivo. GIFBloom non invia questi contenuti a server gestiti dallo sviluppatore. Se utilizzi Foto, iCloud o il pannello di condivisione di iOS, si applicano le pratiche sulla privacy di Apple o del servizio scelto."], ["Archiviazione locale ed esportazioni", "I progetti vengono archiviati localmente nell’app. Scegli tu quando esportare un risultato in Foto o condividerlo con un’altra app. Rimuovere GIFBloom può eliminare i progetti salvati solo sul dispositivo; conserva copie dei contenuti che vuoi mantenere."], ["Autorizzazioni", "GIFBloom utilizza i contenuti che scegli tramite le interfacce di selezione di iOS. iOS potrebbe chiedere l’accesso a Foto quando salvi un’esportazione nella libreria. Puoi gestire le autorizzazioni in Impostazioni iOS."], ["Minori, modifiche e contatti", "GIFBloom non è progettata per raccogliere dati personali dei minori. Potremmo aggiornare questa informativa in caso di modifiche all’app. Per domande sulla privacy, contatta"]]
  },
  ja: {
    label: "日本語", nav: ["ホーム", "サポート", "プライバシー"],
    land: ["思い出に、動きを。", "動画やLive Photosから動く切り抜きを作り、テキスト、エフェクト、音声を重ねてシーンを編集できます。", "iOS 17以降に対応", "人物を切り抜く", "選択した動画やLive Photosから人物をデバイス上で切り抜きます。", "シーンを作る", "複数の素材を重ね、位置・サイズ・回転・表示時間を調整できます。背景、フレーム、ステッカー、テキストも追加できます。", "音声を加えて書き出す", "動画から抽出した音声をタイムラインに配置し、GIF、透明背景のHEVC動画、H.264動画として書き出せます。", "素材はデバイス内に保管されます。GIFBloomが写真や動画をアップロードすることはありません。"],
    support: ["GIFBloom サポート", "メディアの読み込み、切り抜き、編集、書き出しについてご案内します。", "よくある質問", ["どのメディアを使えますか？", "ライブラリから動画、Live Photo、写真を選択できます。GIFBloomはプロジェクト用に選択したメディアを使用します。"], ["人物を切り抜けないのはなぜですか？", "人物の切り抜きにはiOS 17以降が必要です。人物がはっきり写った写真や動画を試し、元のメディアの読み込みが完了していることを確認してください。"], ["どの書き出し形式を選べばよいですか？", "手軽に共有するならGIF、透明背景が必要ならアルファ付きHEVC、幅広い動画互換性が必要ならH.264を選択してください。選べる形式はプロジェクトとデバイスによって異なります。"], ["プロジェクトや書き出したファイルはどこに保存されますか？", "プロジェクトはデバイス上のGIFBloomに保存されます。書き出し時に写真アプリへ保存するか、iOSの共有シートから別のアプリに共有できます。"], "お問い合わせ", "サポートや問題の報告は、次のメールアドレスまでご連絡ください"],
    privacy: ["GIFBloomは選択したメディアをデバイス上で処理します。アプリを通じて個人情報を収集したり、写真や動画を当社のサーバーにアップロードしたりすることはありません。", ["収集する情報", "GIFBloomではアカウント登録は不要です。個人情報、利用状況の分析データ、広告識別子は収集しません。"], ["メディアの処理", "選択した写真、動画、音声、プロジェクトの内容はデバイス上で処理されます。GIFBloomがこれらを開発者のサーバーへ送信することはありません。iOSの写真、iCloud、システム共有シートを利用する場合は、Appleまたは選択したサービスの規約とプライバシー慣行が適用されます。"], ["ローカル保存と書き出し", "プロジェクトはアプリ内にローカル保存されます。写真アプリへの書き出しや他のアプリへの共有は、ユーザーが操作した場合に行われます。GIFBloomを削除すると、デバイスにのみ保存されたプロジェクトが削除される場合があります。残したい内容は別途保存してください。"], ["アクセス許可", "GIFBloomはiOSの選択画面でユーザーが選んだメディアを使用します。書き出した作品をライブラリに保存する際、iOSが写真へのアクセスを求める場合があります。アクセス許可はiOSの設定で管理できます。"], ["お子様、更新、お問い合わせ", "GIFBloomはお子様の個人情報を収集する目的で設計されていません。アプリの変更に伴い本ポリシーを更新することがあります。プライバシーに関するご質問は、こちらまでご連絡ください"]]
  },
  ko: {
    label: "한국어", nav: ["홈", "지원", "개인정보 보호"],
    land: ["순간을 움직임으로 담아보세요.", "동영상과 Live Photo에서 움직이는 인물을 추출하고 텍스트, 효과, 사운드를 더해 여러 레이어의 장면을 만드세요.", "iOS 17 이상 지원", "인물 추출", "선택한 동영상과 Live Photo에서 인물을 기기에서 바로 추출합니다.", "장면 구성", "여러 요소를 겹치고 위치, 크기, 회전, 표시 시간을 조정하세요. 배경, 프레임, 스티커, 텍스트도 추가할 수 있습니다.", "사운드 추가 및 내보내기", "추출한 오디오를 타임라인에 배치하고 GIF, 투명 HEVC 동영상 또는 H.264 동영상으로 내보내세요.", "미디어는 기기에 보관됩니다. GIFBloom은 사진이나 동영상을 업로드하지 않습니다."],
    support: ["GIFBloom 도움말", "미디어 가져오기, 인물 추출, 편집, 내보내기에 관한 답변입니다.", "자주 묻는 질문", ["어떤 미디어를 사용할 수 있나요?", "보관함에서 동영상, Live Photo 또는 사진을 선택하세요. GIFBloom은 프로젝트에 선택한 미디어를 사용합니다."], ["인물 추출이 되지 않는 이유는 무엇인가요?", "인물 추출에는 iOS 17 이상이 필요합니다. 인물이 선명하게 보이는 사진이나 동영상을 사용하고 원본 미디어가 모두 로드되었는지 확인하세요."], ["어떤 내보내기 형식을 선택해야 하나요?", "간편하게 공유하려면 GIF, 투명도가 필요하면 알파 채널이 있는 HEVC, 폭넓은 동영상 호환성이 필요하면 H.264를 선택하세요. 사용할 수 있는 형식은 프로젝트와 기기에 따라 다릅니다."], ["프로젝트와 내보낸 파일은 어디에 저장되나요?", "프로젝트는 기기의 GIFBloom에 로컬로 저장됩니다. 내보낼 때 결과물을 사진 앱에 저장하거나 iOS 공유 시트로 다른 앱에 보낼 수 있습니다."], "문의", "도움이 필요하거나 문제를 신고하려면 다음 이메일로 문의하세요"],
    privacy: ["GIFBloom은 선택한 미디어를 기기에서 처리합니다. 앱을 통해 개인정보를 수집하거나 사진 및 동영상을 서버에 업로드하지 않습니다.", ["수집하는 정보", "GIFBloom은 계정을 요구하지 않으며 개인정보, 사용 분석 데이터, 광고 식별자를 수집하지 않습니다."], ["미디어 처리", "선택한 사진, 동영상, 오디오 및 프로젝트 콘텐츠는 기기에서 처리됩니다. GIFBloom은 이 콘텐츠를 개발자가 운영하는 서버로 보내지 않습니다. iOS 사진, iCloud 또는 시스템 공유 시트를 사용하는 경우 Apple 또는 선택한 서비스의 약관 및 개인정보 처리방침이 적용됩니다."], ["로컬 저장 및 내보내기", "프로젝트는 앱에 로컬로 저장됩니다. 사진 앱으로 내보내거나 다른 앱과 공유할 시점은 사용자가 선택합니다. GIFBloom을 삭제하면 기기에만 저장된 프로젝트가 삭제될 수 있으므로 보관하려는 항목은 별도로 저장하세요."], ["권한", "GIFBloom은 iOS 선택 화면에서 사용자가 고른 미디어를 사용합니다. 보관함에 결과물을 저장할 때 iOS가 사진 접근 권한을 요청할 수 있습니다. iOS 설정에서 권한을 관리할 수 있습니다."], ["아동, 변경 사항 및 문의", "GIFBloom은 아동의 개인정보 수집을 목적으로 설계되지 않았습니다. 앱이 변경되면 이 정책을 업데이트할 수 있습니다. 개인정보 관련 문의는 다음으로 연락해 주세요"]]
  },
  ru: {
    label: "Русский", nav: ["Главная", "Поддержка", "Конфиденциальность"],
    land: ["Оживите свои моменты.", "Превращайте видео и Live Photos в анимированные вырезки и создавайте многослойные сцены с текстом, эффектами и звуком.", "Требуется iOS 17 или новее", "Создавайте вырезки", "Вырезайте людей из выбранных видео и Live Photos прямо на устройстве.", "Собирайте сцены", "Расположите несколько элементов слоями и настройте их положение, размер, поворот и время показа. Добавьте фон, рамки, стикеры и текст.", "Добавляйте звук и экспортируйте", "Разместите извлечённое аудио на шкале времени и экспортируйте результат в GIF, прозрачное видео HEVC или видео H.264.", "Ваши материалы остаются на устройстве. GIFBloom не загружает ваши фото и видео."],
    support: ["Помощь по GIFBloom", "Ответы об импорте материалов, создании вырезок, редактировании и экспорте.", "Часто задаваемые вопросы", ["Какие материалы можно использовать?", "Выберите видео, Live Photo или фото из медиатеки. GIFBloom использует материалы, выбранные для проекта."], ["Почему GIFBloom не может вырезать человека?", "Для вырезания людей требуется iOS 17 или новее. Попробуйте чёткое фото или видео, где хорошо виден человек, и дождитесь загрузки исходного материала."], ["Какой формат экспорта выбрать?", "Выберите GIF для удобного обмена, HEVC с альфа-каналом для прозрачности или H.264 для широкой совместимости видео. Доступные варианты зависят от проекта и устройства."], ["Где хранятся проекты и экспортированные файлы?", "Проекты хранятся локально в GIFBloom на устройстве. При экспорте можно сохранить результат в Фото или отправить его в другое приложение через меню «Поделиться» в iOS."], "Контакты", "Если нужна помощь или вы хотите сообщить о проблеме, напишите нам"],
    privacy: ["GIFBloom обрабатывает выбранные материалы на вашем устройстве. Мы не собираем персональные данные через приложение и не загружаем ваши фото и видео на наши серверы.", ["Какие данные мы собираем", "Для GIFBloom не нужна учётная запись. Приложение не собирает персональные данные, аналитику использования или рекламные идентификаторы."], ["Обработка материалов", "Выбранные фото, видео, аудио и содержимое проектов обрабатываются на устройстве. GIFBloom не отправляет их на серверы разработчика. При использовании Фото в iOS, iCloud или системного меню отправки действуют условия и политика конфиденциальности Apple или выбранного сервиса."], ["Локальное хранение и экспорт", "Проекты хранятся локально в приложении. Вы сами выбираете, когда экспортировать результат в Фото или отправлять его в другое приложение. Удаление GIFBloom может удалить проекты, сохранённые только на устройстве; сохраните копии нужных материалов."], ["Разрешения", "GIFBloom использует материалы, выбранные через интерфейсы выбора iOS. При сохранении результата в медиатеку iOS может запросить доступ к Фото. Разрешениями можно управлять в настройках iOS."], ["Дети, изменения и контакты", "GIFBloom не предназначено для сбора персональных данных детей. При изменении приложения мы можем обновлять эту политику. По вопросам конфиденциальности свяжитесь с нами"]]
  },
  "pt-BR": {
    label: "Português (Brasil)", nav: ["Início", "Suporte", "Privacidade"],
    land: ["Dê movimento aos seus momentos.", "Transforme vídeos e Live Photos em recortes animados e crie cenas em camadas com texto, efeitos e som.", "Para iOS 17 ou posterior", "Crie recortes", "Recorte pessoas de vídeos e Live Photos selecionados diretamente no dispositivo.", "Monte uma cena", "Sobreponha vários elementos e ajuste posição, tamanho, rotação e duração. Adicione fundos, molduras, figurinhas e texto.", "Adicione som e exporte", "Coloque o áudio extraído na linha do tempo e exporte como GIF, vídeo HEVC transparente ou vídeo H.264.", "Seus arquivos permanecem no dispositivo. O GIFBloom não envia suas fotos ou vídeos."],
    support: ["Ajuda do GIFBloom", "Respostas sobre importação de mídia, criação de recortes, edição e exportação.", "Perguntas frequentes", ["Quais mídias posso usar?", "Escolha um vídeo, Live Photo ou foto da sua biblioteca. O GIFBloom usa as mídias selecionadas para o projeto."], ["Por que o GIFBloom não consegue criar um recorte?", "O recorte de pessoas requer iOS 17 ou posterior. Experimente uma foto ou um vídeo nítido com uma pessoa visível e aguarde o carregamento da mídia original."], ["Qual formato de exportação devo escolher?", "Escolha GIF para compartilhar facilmente, HEVC com alpha quando precisar de transparência ou H.264 para ampla compatibilidade de vídeo. As opções dependem do projeto e do dispositivo."], ["Onde meus projetos e arquivos exportados são salvos?", "Os projetos são salvos localmente no GIFBloom no seu dispositivo. Ao exportar, escolha salvar o resultado no app Fotos ou compartilhá-lo com outro app pela folha de compartilhamento do iOS."], "Contato", "Para obter ajuda ou relatar um problema, envie um e-mail para"],
    privacy: ["O GIFBloom processa as mídias selecionadas no seu dispositivo. Não coletamos dados pessoais pelo app nem enviamos suas fotos ou vídeos aos nossos servidores.", ["Informações coletadas", "O GIFBloom não exige uma conta e não coleta dados pessoais, análises de uso ou identificadores de publicidade."], ["Processamento de mídia", "Fotos, vídeos, áudios e conteúdos de projetos selecionados são processados no dispositivo. O GIFBloom não envia esse conteúdo a servidores operados pelo desenvolvedor. Se você usar Fotos do iOS, iCloud ou a folha de compartilhamento do sistema, aplicam-se os termos e práticas de privacidade da Apple ou do serviço escolhido."], ["Armazenamento local e exportações", "Os projetos ficam armazenados localmente no app. Você escolhe quando exportar um resultado para Fotos ou compartilhá-lo com outro app. A remoção do GIFBloom pode apagar projetos armazenados somente no dispositivo; mantenha cópias do que quiser guardar."], ["Permissões", "O GIFBloom usa as mídias que você escolhe pelas interfaces de seleção do iOS. O iOS pode solicitar acesso ao Fotos quando você salvar uma exportação na biblioteca. Gerencie as permissões nos Ajustes do iOS."], ["Crianças, alterações e contato", "O GIFBloom não foi criado para coletar dados pessoais de crianças. Podemos atualizar esta política se o app mudar. Para dúvidas sobre privacidade, entre em contato"]]
  },
  ar: {
    label: "العربية", nav: ["الرئيسية", "الدعم", "الخصوصية"],
    land: ["اجعل لحظاتك تنبض بالحركة.", "حوّل مقاطع الفيديو وLive Photo إلى قصاصات متحركة، ثم أنشئ مشاهد متعددة الطبقات بالنصوص والتأثيرات والصوت.", "يتطلب iOS 17 أو أحدث", "أنشئ قصاصات", "استخرج الأشخاص من مقاطع الفيديو وLive Photo التي تختارها مباشرة على جهازك.", "كوّن مشهدًا", "رتّب عدة عناصر في طبقات واضبط مواضعها وأحجامها ودورانها وتوقيت ظهورها. أضف خلفيات وإطارات وملصقات ونصوصًا.", "أضف الصوت وصدّر", "ضع الصوت المستخرج على المخطط الزمني وصدّر بصيغة GIF أو فيديو HEVC شفاف أو فيديو H.264.", "تظل الوسائط على جهازك. لا يرفع GIFBloom صورك أو مقاطع الفيديو الخاصة بك."],
    support: ["مساعدة GIFBloom", "إجابات حول استيراد الوسائط وإنشاء القصاصات والتحرير والتصدير.", "الأسئلة الشائعة", ["ما الوسائط التي يمكنني استخدامها؟", "اختر مقطع فيديو أو Live Photo أو صورة من مكتبتك. يستخدم GIFBloom الوسائط التي تختارها لمشروعك."], ["لماذا لا يستطيع GIFBloom إنشاء قصاصة؟", "يتطلب استخراج الأشخاص نظام iOS 17 أو أحدث. جرّب صورة أو مقطع فيديو واضحًا يظهر فيه الشخص، وانتظر حتى يكتمل تحميل الوسائط الأصلية."], ["ما صيغة التصدير التي أختارها؟", "اختر GIF للمشاركة بسهولة، أو HEVC بقناة ألفا عند الحاجة إلى الشفافية، أو H.264 لتوافق أوسع مع الفيديو. تعتمد الخيارات على المشروع والجهاز."], ["أين تُحفظ مشاريعي والملفات التي أصدّرها؟", "تُحفظ المشاريع محليًا في GIFBloom على جهازك. عند التصدير، يمكنك حفظ النتيجة في الصور أو مشاركتها مع تطبيق آخر باستخدام قائمة المشاركة في iOS."], "اتصل بنا", "للحصول على المساعدة أو الإبلاغ عن مشكلة، راسلنا عبر البريد الإلكتروني"],
    privacy: ["يعالج GIFBloom الوسائط التي تختارها على جهازك. لا نجمع معلومات شخصية عبر التطبيق ولا نرفع صورك أو مقاطع الفيديو إلى خوادمنا.", ["المعلومات التي نجمعها", "لا يتطلب GIFBloom إنشاء حساب ولا يجمع معلومات شخصية أو بيانات تحليل الاستخدام أو معرّفات الإعلانات."], ["معالجة الوسائط", "تُعالج الصور ومقاطع الفيديو والصوت ومحتويات المشاريع التي تختارها على جهازك. لا يرسل GIFBloom هذه المحتويات إلى خوادم يديرها المطور. عند استخدام الصور في iOS أو iCloud أو قائمة المشاركة، تسري شروط وممارسات الخصوصية الخاصة بـ Apple أو الخدمة التي تختارها."], ["التخزين المحلي والتصدير", "تُخزّن المشاريع محليًا داخل التطبيق. أنت تختار وقت تصدير النتيجة إلى الصور أو مشاركتها مع تطبيق آخر. قد يؤدي حذف GIFBloom إلى إزالة المشاريع المخزنة على الجهاز فقط؛ احتفظ بنسخ من المحتوى الذي تريد الاحتفاظ به."], ["الأذونات", "يستخدم GIFBloom الوسائط التي تختارها عبر واجهات الاختيار في iOS. قد يطلب iOS إذن الوصول إلى الصور عند حفظ ملف مُصدّر في مكتبتك. يمكنك إدارة الأذونات من إعدادات iOS."], ["الأطفال والتحديثات والتواصل", "لم يُصمم GIFBloom لجمع معلومات شخصية عن الأطفال. قد نحدّث هذه السياسة عند تغيير التطبيق. لطرح أسئلة حول الخصوصية، يُرجى التواصل معنا عبر"]]
  },
  hi: {
    label: "हिन्दी", nav: ["होम", "सहायता", "गोपनीयता"],
    land: ["अपने पलों को जीवंत बनाएं।", "वीडियो और Live Photo से चलती कटआउट बनाएं, फिर टेक्स्ट, इफेक्ट और ध्वनि के साथ परतदार दृश्य तैयार करें।", "iOS 17 या बाद का संस्करण आवश्यक", "कटआउट बनाएं", "चुने हुए वीडियो और Live Photo से व्यक्ति को सीधे अपने डिवाइस पर अलग करें।", "दृश्य बनाएं", "कई तत्वों को परतों में रखें और उनकी जगह, आकार, घुमाव और समय बदलें। बैकग्राउंड, फ्रेम, स्टिकर और टेक्स्ट जोड़ें।", "ध्वनि जोड़ें और निर्यात करें", "निकाली गई ध्वनि को टाइमलाइन पर रखें और GIF, पारदर्शी HEVC वीडियो या H.264 वीडियो के रूप में निर्यात करें।", "आपका मीडिया आपके डिवाइस पर रहता है। GIFBloom आपकी फ़ोटो या वीडियो अपलोड नहीं करता।"],
    support: ["GIFBloom सहायता", "मीडिया आयात करने, कटआउट बनाने, संपादन और निर्यात से जुड़े जवाब।", "अक्सर पूछे जाने वाले सवाल", ["मैं कौन-सा मीडिया इस्तेमाल कर सकता हूं?", "अपनी लाइब्रेरी से वीडियो, Live Photo या फ़ोटो चुनें। GIFBloom आपके प्रोजेक्ट के लिए चुने गए मीडिया का उपयोग करता है।"], ["GIFBloom कटआउट क्यों नहीं बना पा रहा?", "व्यक्ति को अलग करने के लिए iOS 17 या बाद का संस्करण चाहिए। स्पष्ट व्यक्ति वाली फ़ोटो या वीडियो आज़माएं और स्रोत मीडिया के पूरी तरह लोड होने की प्रतीक्षा करें।"], ["कौन-सा निर्यात प्रारूप चुनूं?", "आसानी से साझा करने के लिए GIF, पारदर्शिता के लिए alpha वाला HEVC, या व्यापक वीडियो संगतता के लिए H.264 चुनें। उपलब्ध विकल्प प्रोजेक्ट और डिवाइस पर निर्भर हैं।"], ["मेरे प्रोजेक्ट और निर्यात कहां सहेजे जाते हैं?", "प्रोजेक्ट आपके डिवाइस पर GIFBloom में स्थानीय रूप से सहेजे जाते हैं। निर्यात करते समय, परिणाम Photos में सहेजें या iOS शेयर शीट से किसी अन्य ऐप में साझा करें।"], "संपर्क", "सहायता या समस्या की रिपोर्ट के लिए हमें ईमेल करें"],
    privacy: ["GIFBloom चुने हुए मीडिया को आपके डिवाइस पर संसाधित करता है। हम ऐप से व्यक्तिगत जानकारी एकत्र नहीं करते और आपकी फ़ोटो या वीडियो अपने सर्वर पर अपलोड नहीं करते।", ["हम कौन-सी जानकारी एकत्र करते हैं", "GIFBloom के लिए खाता बनाना आवश्यक नहीं है। यह व्यक्तिगत जानकारी, उपयोग विश्लेषण या विज्ञापन पहचानकर्ता एकत्र नहीं करता।"], ["मीडिया संसाधन", "चुनी गई फ़ोटो, वीडियो, ऑडियो और प्रोजेक्ट सामग्री आपके डिवाइस पर संसाधित होती है। GIFBloom इसे डेवलपर द्वारा संचालित सर्वर पर नहीं भेजता। iOS Photos, iCloud या सिस्टम शेयर शीट का उपयोग करने पर Apple या चुनी हुई सेवा की शर्तें और गोपनीयता नियम लागू होते हैं।"], ["स्थानीय संग्रहण और निर्यात", "प्रोजेक्ट ऐप में स्थानीय रूप से सहेजे जाते हैं। आप तय करते हैं कि परिणाम Photos में कब निर्यात करना है या किसी अन्य ऐप से साझा करना है। GIFBloom हटाने पर केवल डिवाइस में रखे प्रोजेक्ट मिट सकते हैं; जिन चीज़ों को रखना चाहते हैं उनकी प्रतियां सहेजें।"], ["अनुमतियां", "GIFBloom iOS चयन इंटरफ़ेस से आपके चुने हुए मीडिया का उपयोग करता है। निर्यात को लाइब्रेरी में सहेजते समय iOS Photos का एक्सेस मांग सकता है। अनुमतियां iOS सेटिंग्स में प्रबंधित करें।"], ["बच्चे, बदलाव और संपर्क", "GIFBloom बच्चों की व्यक्तिगत जानकारी एकत्र करने के लिए नहीं बनाया गया है। ऐप बदलने पर हम इस नीति को अपडेट कर सकते हैं। गोपनीयता संबंधी प्रश्नों के लिए संपर्क करें"]]
  },
  id: {
    label: "Bahasa Indonesia", nav: ["Beranda", "Dukungan", "Privasi"],
    land: ["Hidupkan momen Anda.", "Ubah video dan Live Photo menjadi potongan bergerak, lalu susun adegan berlapis dengan teks, efek, dan suara.", "Memerlukan iOS 17 atau lebih baru", "Buat potongan", "Potong orang dari video dan Live Photo pilihan langsung di perangkat Anda.", "Susun adegan", "Tumpuk beberapa elemen dan atur posisi, ukuran, rotasi, serta waktunya. Tambahkan latar, bingkai, stiker, dan teks.", "Tambahkan suara dan ekspor", "Tempatkan audio hasil ekstraksi di timeline, lalu ekspor sebagai GIF, video HEVC transparan, atau video H.264.", "Media tetap ada di perangkat Anda. GIFBloom tidak mengunggah foto atau video Anda."],
    support: ["Bantuan GIFBloom", "Jawaban tentang mengimpor media, membuat potongan, mengedit, dan mengekspor.", "Pertanyaan umum", ["Media apa yang dapat digunakan?", "Pilih video, Live Photo, atau foto dari perpustakaan Anda. GIFBloom menggunakan media yang dipilih untuk proyek."], ["Mengapa GIFBloom tidak dapat membuat potongan?", "Pemotongan orang memerlukan iOS 17 atau lebih baru. Coba foto atau video yang jelas dengan orang terlihat dan tunggu sampai media sumber selesai dimuat."], ["Format ekspor mana yang sebaiknya dipilih?", "Pilih GIF agar mudah dibagikan, HEVC dengan alpha jika memerlukan transparansi, atau H.264 untuk kompatibilitas video yang luas. Pilihan yang tersedia bergantung pada proyek dan perangkat."], ["Di mana proyek dan hasil ekspor disimpan?", "Proyek disimpan secara lokal di GIFBloom pada perangkat Anda. Saat mengekspor, pilih untuk menyimpan hasil ke Foto atau membagikannya ke aplikasi lain melalui lembar berbagi iOS."], "Kontak", "Untuk bantuan atau melaporkan masalah, kirim email ke"],
    privacy: ["GIFBloom memproses media pilihan Anda di perangkat. Kami tidak mengumpulkan informasi pribadi melalui app atau mengunggah foto maupun video Anda ke server kami.", ["Informasi yang kami kumpulkan", "GIFBloom tidak memerlukan akun dan tidak mengumpulkan informasi pribadi, analitik penggunaan, atau pengenal iklan."], ["Pemrosesan media", "Foto, video, audio, dan konten proyek yang dipilih diproses di perangkat. GIFBloom tidak mengirim konten ini ke server yang dikelola pengembang. Jika Anda menggunakan Foto iOS, iCloud, atau lembar berbagi sistem, ketentuan dan praktik privasi Apple atau layanan pilihan berlaku."], ["Penyimpanan lokal dan ekspor", "Proyek disimpan secara lokal di app. Anda memilih kapan mengekspor hasil ke Foto atau membagikannya ke app lain. Menghapus GIFBloom dapat menghapus proyek yang hanya tersimpan di perangkat; simpan salinan konten yang ingin dipertahankan."], ["Izin", "GIFBloom menggunakan media yang Anda pilih melalui antarmuka pemilihan iOS. iOS dapat meminta akses Foto saat Anda menyimpan hasil ekspor ke perpustakaan. Kelola izin di Pengaturan iOS."], ["Anak-anak, perubahan, dan kontak", "GIFBloom tidak dirancang untuk mengumpulkan informasi pribadi anak-anak. Kami dapat memperbarui kebijakan ini jika app berubah. Untuk pertanyaan privasi, hubungi"]]
  },
  th: {
    label: "ไทย", nav: ["หน้าแรก", "การสนับสนุน", "ความเป็นส่วนตัว"],
    land: ["เปลี่ยนช่วงเวลาให้เคลื่อนไหว", "เปลี่ยนวิดีโอและ Live Photo ให้เป็นภาพบุคคลแบบเคลื่อนไหว แล้วจัดวางเป็นฉากหลายชั้นพร้อมข้อความ เอฟเฟ็กต์ และเสียง", "ต้องใช้ iOS 17 ขึ้นไป", "สร้างภาพตัด", "แยกบุคคลจากวิดีโอและ Live Photo ที่เลือกบนอุปกรณ์ของคุณ", "จัดองค์ประกอบฉาก", "วางองค์ประกอบหลายชั้นและปรับตำแหน่ง ขนาด การหมุน และช่วงเวลา เพิ่มพื้นหลัง กรอบ สติกเกอร์ และข้อความ", "เพิ่มเสียงและส่งออก", "วางเสียงที่แยกไว้บนไทม์ไลน์ แล้วส่งออกเป็น GIF วิดีโอ HEVC โปร่งใส หรือวิดีโอ H.264", "สื่อของคุณอยู่บนอุปกรณ์ GIFBloom จะไม่อัปโหลดรูปภาพหรือวิดีโอของคุณ"],
    support: ["ความช่วยเหลือ GIFBloom", "คำตอบเกี่ยวกับการนำเข้าสื่อ การสร้างภาพตัด การแก้ไข และการส่งออก", "คำถามที่พบบ่อย", ["ใช้สื่อประเภทใดได้บ้าง?", "เลือกวิดีโอ Live Photo หรือรูปภาพจากคลังของคุณ GIFBloom จะใช้สื่อที่คุณเลือกสำหรับโปรเจ็กต์"], ["เหตุใด GIFBloom จึงสร้างภาพตัดไม่ได้?", "การแยกบุคคลต้องใช้ iOS 17 ขึ้นไป ลองใช้รูปภาพหรือวิดีโอที่เห็นบุคคลชัดเจน และรอให้โหลดสื่อต้นฉบับเสร็จ"], ["ควรเลือกรูปแบบส่งออกแบบใด?", "เลือก GIF เพื่อแชร์ได้ง่าย เลือก HEVC ที่มี alpha เมื่อต้องการความโปร่งใส หรือเลือก H.264 เพื่อรองรับวิดีโอได้กว้าง ตัวเลือกขึ้นอยู่กับโปรเจ็กต์และอุปกรณ์"], ["โปรเจ็กต์และไฟล์ที่ส่งออกบันทึกไว้ที่ใด?", "โปรเจ็กต์จะบันทึกไว้ใน GIFBloom บนอุปกรณ์ของคุณ เมื่อส่งออก คุณเลือกบันทึกผลลัพธ์ไปยัง Photos หรือแชร์ไปยังแอปอื่นผ่านเมนูแชร์ของ iOS ได้"], "ติดต่อ", "หากต้องการความช่วยเหลือหรือรายงานปัญหา โปรดส่งอีเมลถึง"],
    privacy: ["GIFBloom ประมวลผลสื่อที่คุณเลือกบนอุปกรณ์ เราไม่เก็บข้อมูลส่วนบุคคลผ่านแอปและไม่อัปโหลดรูปภาพหรือวิดีโอของคุณไปยังเซิร์ฟเวอร์ของเรา", ["ข้อมูลที่เราเก็บ", "GIFBloom ไม่ต้องใช้บัญชีและไม่เก็บข้อมูลส่วนบุคคล ข้อมูลวิเคราะห์การใช้งาน หรือรหัสโฆษณา"], ["การประมวลผลสื่อ", "รูปภาพ วิดีโอ เสียง และเนื้อหาโปรเจ็กต์ที่เลือกจะประมวลผลบนอุปกรณ์ GIFBloom จะไม่ส่งเนื้อหาเหล่านี้ไปยังเซิร์ฟเวอร์ที่ผู้พัฒนาดูแล หากคุณใช้ Photos, iCloud หรือเมนูแชร์ของระบบ จะเป็นไปตามข้อกำหนดและแนวปฏิบัติด้านความเป็นส่วนตัวของ Apple หรือบริการที่เลือก"], ["การจัดเก็บในเครื่องและการส่งออก", "โปรเจ็กต์จะจัดเก็บไว้ในแอปบนอุปกรณ์ คุณเลือกได้ว่าจะส่งออกไปยัง Photos หรือแชร์กับแอปอื่นเมื่อใด การลบ GIFBloom อาจลบโปรเจ็กต์ที่จัดเก็บไว้เฉพาะในอุปกรณ์ โปรดสำรองเนื้อหาที่ต้องการเก็บไว้"], ["สิทธิ์การเข้าถึง", "GIFBloom ใช้สื่อที่คุณเลือกผ่านหน้าจอเลือกของ iOS iOS อาจขอสิทธิ์เข้าถึง Photos เมื่อบันทึกไฟล์ที่ส่งออกไปยังคลัง คุณจัดการสิทธิ์ได้ในการตั้งค่า iOS"], ["เด็ก การเปลี่ยนแปลง และการติดต่อ", "GIFBloom ไม่ได้ออกแบบมาเพื่อเก็บข้อมูลส่วนบุคคลของเด็ก เราอาจปรับปรุงนโยบายนี้เมื่อแอปเปลี่ยนแปลง หากมีคำถามด้านความเป็นส่วนตัว โปรดติดต่อ"]]
  },
  tr: {
    label: "Türkçe", nav: ["Ana Sayfa", "Destek", "Gizlilik"],
    land: ["Anılarınıza hareket katın.", "Videoları ve Live Photo’ları hareketli kesitlere dönüştürün; metin, efekt ve sesle katmanlı sahneler oluşturun.", "iOS 17 veya üzeri gerekir", "Kesit oluşturun", "Seçtiğiniz video ve Live Photo’lardan kişileri doğrudan cihazınızda ayırın.", "Bir sahne oluşturun", "Birden fazla öğeyi katmanlayıp konum, boyut, dönüş ve zamanlamayı ayarlayın. Arka plan, çerçeve, çıkartma ve metin ekleyin.", "Ses ekleyip dışa aktarın", "Çıkarılan sesi zaman çizelgesine yerleştirin ve GIF, şeffaf HEVC video veya H.264 video olarak dışa aktarın.", "Medyanız cihazınızda kalır. GIFBloom fotoğraf ve videolarınızı yüklemez."],
    support: ["GIFBloom Yardım", "Medya içe aktarma, kesit oluşturma, düzenleme ve dışa aktarma hakkında yanıtlar.", "Sık sorulan sorular", ["Hangi medyaları kullanabilirim?", "Kitaplığınızdan video, Live Photo veya fotoğraf seçin. GIFBloom projeniz için seçtiğiniz medyayı kullanır."], ["GIFBloom neden kesit oluşturamıyor?", "Kişi kesme özelliği için iOS 17 veya üzeri gerekir. Kişinin net göründüğü bir fotoğraf ya da video deneyin ve kaynak medyanın yüklenmesini bekleyin."], ["Hangi dışa aktarma biçimini seçmeliyim?", "Kolay paylaşım için GIF’i, şeffaflık için alpha kanallı HEVC’yi veya geniş video uyumluluğu için H.264’ü seçin. Seçenekler projeye ve cihaza bağlıdır."], ["Projelerim ve dışa aktardıklarım nereye kaydediliyor?", "Projeler cihazınızdaki GIFBloom’a yerel olarak kaydedilir. Dışa aktarırken sonucu Fotoğraflar’a kaydedebilir veya iOS paylaşım menüsüyle başka bir uygulamaya gönderebilirsiniz."], "İletişim", "Yardım almak veya bir sorunu bildirmek için bize e-posta gönderin"],
    privacy: ["GIFBloom seçtiğiniz medyayı cihazınızda işler. Uygulama üzerinden kişisel bilgi toplamayız ve fotoğraf ya da videolarınızı sunucularımıza yüklemeyiz.", ["Topladığımız bilgiler", "GIFBloom hesap gerektirmez; kişisel bilgi, kullanım analitiği veya reklam tanımlayıcısı toplamaz."], ["Medya işleme", "Seçtiğiniz fotoğraf, video, ses ve proje içerikleri cihazınızda işlenir. GIFBloom bu içerikleri geliştirici tarafından işletilen sunuculara göndermez. iOS Fotoğraflar, iCloud veya sistem paylaşım menüsünü kullanırsanız Apple’ın ya da seçtiğiniz hizmetin koşulları ve gizlilik uygulamaları geçerlidir."], ["Yerel saklama ve dışa aktarma", "Projeler uygulamada yerel olarak saklanır. Bir sonucu Fotoğraflar’a ne zaman aktaracağınıza veya başka bir uygulamayla paylaşacağınıza siz karar verirsiniz. GIFBloom’u kaldırmak yalnızca cihazda saklanan projeleri silebilir; saklamak istediklerinizin bir kopyasını alın."], ["İzinler", "GIFBloom, iOS seçim arayüzlerinden seçtiğiniz medyayı kullanır. Dışa aktarılan bir sonucu kitaplığa kaydederken iOS Fotoğraflar erişimi isteyebilir. İzinleri iOS Ayarları’ndan yönetebilirsiniz."], ["Çocuklar, değişiklikler ve iletişim", "GIFBloom çocuklardan kişisel bilgi toplamak üzere tasarlanmamıştır. Uygulama değişirse bu politikayı güncelleyebiliriz. Gizlilik sorularınız için bize ulaşın"]]
  },
  vi: {
    label: "Tiếng Việt", nav: ["Trang chủ", "Hỗ trợ", "Quyền riêng tư"],
    land: ["Thêm chuyển động cho khoảnh khắc của bạn.", "Biến video và Live Photo thành ảnh cắt chuyển động, rồi ghép thành cảnh nhiều lớp với chữ, hiệu ứng và âm thanh.", "Yêu cầu iOS 17 trở lên", "Tạo ảnh cắt", "Tách người từ video và Live Photo bạn chọn ngay trên thiết bị.", "Dựng cảnh", "Xếp nhiều lớp và điều chỉnh vị trí, kích thước, góc xoay, thời gian. Thêm nền, khung, nhãn dán và văn bản.", "Thêm âm thanh và xuất", "Đặt âm thanh trích xuất vào dòng thời gian, rồi xuất thành GIF, video HEVC trong suốt hoặc video H.264.", "Nội dung của bạn luôn ở trên thiết bị. GIFBloom không tải ảnh hoặc video của bạn lên."],
    support: ["Trợ giúp GIFBloom", "Giải đáp về nhập phương tiện, tạo ảnh cắt, chỉnh sửa và xuất tệp.", "Câu hỏi thường gặp", ["Tôi có thể dùng loại phương tiện nào?", "Chọn video, Live Photo hoặc ảnh từ thư viện. GIFBloom sử dụng nội dung bạn chọn cho dự án."], ["Vì sao GIFBloom không thể tạo ảnh cắt?", "Tính năng tách người yêu cầu iOS 17 trở lên. Hãy thử ảnh hoặc video rõ nét có người xuất hiện và đợi phương tiện gốc tải xong."], ["Tôi nên chọn định dạng xuất nào?", "Chọn GIF để chia sẻ dễ dàng, HEVC có alpha khi cần độ trong suốt hoặc H.264 để tương thích video rộng hơn. Tùy chọn có thể thay đổi theo dự án và thiết bị."], ["Dự án và tệp đã xuất được lưu ở đâu?", "Dự án được lưu cục bộ trong GIFBloom trên thiết bị. Khi xuất, bạn có thể lưu kết quả vào Ảnh hoặc chia sẻ với ứng dụng khác bằng bảng chia sẻ của iOS."], "Liên hệ", "Để được trợ giúp hoặc báo cáo sự cố, hãy gửi email đến"],
    privacy: ["GIFBloom xử lý nội dung bạn chọn ngay trên thiết bị. Chúng tôi không thu thập thông tin cá nhân qua ứng dụng hoặc tải ảnh và video lên máy chủ của mình.", ["Thông tin chúng tôi thu thập", "GIFBloom không yêu cầu tài khoản và không thu thập thông tin cá nhân, dữ liệu phân tích sử dụng hoặc mã nhận dạng quảng cáo."], ["Xử lý phương tiện", "Ảnh, video, âm thanh và nội dung dự án bạn chọn được xử lý trên thiết bị. GIFBloom không gửi nội dung này đến máy chủ do nhà phát triển vận hành. Nếu dùng Ảnh của iOS, iCloud hoặc bảng chia sẻ hệ thống, các điều khoản và chính sách riêng tư của Apple hoặc dịch vụ được chọn sẽ áp dụng."], ["Lưu trữ cục bộ và xuất", "Dự án được lưu cục bộ trong ứng dụng. Bạn chọn thời điểm xuất kết quả vào Ảnh hoặc chia sẻ với ứng dụng khác. Việc xóa GIFBloom có thể xóa các dự án chỉ lưu trên thiết bị; hãy lưu bản sao nội dung bạn muốn giữ."], ["Quyền truy cập", "GIFBloom dùng nội dung bạn chọn qua giao diện chọn của iOS. iOS có thể yêu cầu quyền truy cập Ảnh khi bạn lưu kết quả xuất vào thư viện. Bạn có thể quản lý quyền trong Cài đặt iOS."], ["Trẻ em, cập nhật và liên hệ", "GIFBloom không được thiết kế để thu thập thông tin cá nhân của trẻ em. Chúng tôi có thể cập nhật chính sách khi ứng dụng thay đổi. Nếu có câu hỏi về quyền riêng tư, vui lòng liên hệ"]]
  }
};

const purchasePrivacy = {
  en: ["In-app purchases", "GIFBloom offers an optional weekly auto-renewable subscription and a one-time lifetime purchase. Apple processes App Store billing and payment information. GIFBloom does not receive card or payment account details. The app uses StoreKit purchase entitlement information to provide access and restore purchases; Apple’s privacy policy applies to payment processing."],
  "zh-Hans": ["App 内购买", "GIFBloom 提供可选的周自动续订订阅和一次性永久买断。App Store 的账单与付款信息由 Apple 处理，GIFBloom 不会收到银行卡或付款账户详情。App 会通过 StoreKit 使用购买权益信息来提供访问权限和恢复购买；付款处理适用 Apple 的隐私政策。"],
  "zh-Hant": ["App 內購買", "GIFBloom 提供可選的每週自動續訂訂閱和一次性永久買斷。App Store 的帳單與付款資訊由 Apple 處理，GIFBloom 不會收到信用卡或付款帳戶詳細資料。App 會透過 StoreKit 使用購買權益資訊來提供存取權限和還原購買；付款處理適用 Apple 的隱私權政策。"],
  de: ["In-App-Käufe", "GIFBloom bietet optional ein automatisch verlängerndes Wochenabo und einen einmaligen Kauf mit dauerhaftem Zugriff an. Apple verarbeitet Abrechnung und Zahlungsdaten im App Store. GIFBloom erhält keine Karten- oder Zahlungskontodaten. Die App verwendet über StoreKit bereitgestellte Informationen zu Kaufberechtigungen, um den Zugriff zu ermöglichen und Käufe wiederherzustellen. Für die Zahlungsabwicklung gilt Apples Datenschutzrichtlinie."],
  es: ["Compras dentro de la app", "GIFBloom ofrece una suscripción semanal opcional con renovación automática y una compra única con acceso permanente. Apple procesa la facturación y los datos de pago del App Store. GIFBloom no recibe los datos de tu tarjeta ni de tu cuenta de pago. La app utiliza la información de derechos de compra de StoreKit para conceder acceso y restaurar compras. Para el procesamiento de pagos se aplica la política de privacidad de Apple."],
  fr: ["Achats intégrés", "GIFBloom propose un abonnement hebdomadaire facultatif à renouvellement automatique et un achat unique donnant un accès permanent. Apple traite la facturation et les informations de paiement de l’App Store. GIFBloom ne reçoit pas les coordonnées de votre carte ni de votre compte de paiement. L’app utilise les informations d’achat fournies par StoreKit pour accorder l’accès et restaurer les achats. La politique de confidentialité d’Apple s’applique au traitement des paiements."],
  it: ["Acquisti in-app", "GIFBloom offre un abbonamento settimanale facoltativo con rinnovo automatico e un acquisto una tantum con accesso permanente. Apple gestisce la fatturazione e i dati di pagamento dell’App Store. GIFBloom non riceve i dati della carta o del conto di pagamento. L’app utilizza le informazioni sui diritti di acquisto fornite da StoreKit per concedere l’accesso e ripristinare gli acquisti. Al trattamento dei pagamenti si applica l’informativa sulla privacy di Apple."],
  ja: ["アプリ内課金", "GIFBloom では、任意の週額自動更新サブスクリプションと、永続アクセスを得られる一度限りの購入を提供しています。App Store の請求と支払い情報は Apple が処理します。GIFBloom がカード情報や決済アカウント情報を受け取ることはありません。アプリは StoreKit の購入権利情報を使ってアクセスを提供し、購入を復元します。支払い処理には Apple のプライバシーポリシーが適用されます。"],
  ko: ["앱 내 구입", "GIFBloom은 선택 가능한 주간 자동 갱신 구독과 영구 이용을 위한 일회성 구매를 제공합니다. App Store 청구 및 결제 정보는 Apple이 처리합니다. GIFBloom은 카드 또는 결제 계정 정보를 받지 않습니다. 앱은 StoreKit의 구매 권한 정보를 사용해 이용 권한을 제공하고 구매를 복원합니다. 결제 처리에는 Apple의 개인정보 처리방침이 적용됩니다."],
  ru: ["Встроенные покупки", "GIFBloom предлагает необязательную недельную подписку с автоматическим продлением и разовую покупку с постоянным доступом. Apple обрабатывает платежи и платёжные данные App Store. GIFBloom не получает данные банковской карты или платёжной учётной записи. Приложение использует сведения о правах покупки от StoreKit, чтобы предоставить доступ и восстановить покупки. К обработке платежей применяется политика конфиденциальности Apple."],
  "pt-BR": ["Compras dentro do app", "O GIFBloom oferece uma assinatura semanal opcional com renovação automática e uma compra única com acesso permanente. A Apple processa a cobrança e as informações de pagamento da App Store. O GIFBloom não recebe os dados do cartão ou da conta de pagamento. O app usa as informações de direitos de compra do StoreKit para conceder acesso e restaurar compras. A política de privacidade da Apple se aplica ao processamento de pagamentos."],
  ar: ["عمليات الشراء داخل التطبيق", "يوفر GIFBloom اشتراكًا أسبوعيًا اختياريًا يتجدد تلقائيًا وشراءً لمرة واحدة يتيح الوصول الدائم. تتولى Apple معالجة الفوترة ومعلومات الدفع في App Store. لا تتلقى GIFBloom تفاصيل البطاقة أو حساب الدفع. يستخدم التطبيق معلومات استحقاق الشراء من StoreKit لتوفير الوصول واستعادة المشتريات. تنطبق سياسة خصوصية Apple على معالجة الدفع."],
  hi: ["ऐप के भीतर खरीदारी", "GIFBloom वैकल्पिक साप्ताहिक स्वतः नवीनीकृत होने वाली सदस्यता और स्थायी पहुँच के लिए एकमुश्त खरीद प्रदान करता है। App Store की बिलिंग और भुगतान जानकारी Apple संभालता है। GIFBloom को कार्ड या भुगतान खाते का विवरण नहीं मिलता। ऐप पहुँच देने और खरीदारी पुनर्स्थापित करने के लिए StoreKit की खरीद पात्रता जानकारी का उपयोग करता है। भुगतान प्रक्रिया पर Apple की गोपनीयता नीति लागू होती है।"],
  id: ["Pembelian dalam app", "GIFBloom menawarkan langganan mingguan opsional yang diperpanjang otomatis dan pembelian satu kali untuk akses permanen. Apple memproses penagihan dan informasi pembayaran App Store. GIFBloom tidak menerima detail kartu atau akun pembayaran. Aplikasi menggunakan informasi hak pembelian dari StoreKit untuk memberikan akses dan memulihkan pembelian. Kebijakan privasi Apple berlaku untuk pemrosesan pembayaran."],
  th: ["การซื้อภายในแอป", "GIFBloom มีตัวเลือกการสมัครสมาชิกรายสัปดาห์ที่ต่ออายุอัตโนมัติและการซื้อครั้งเดียวเพื่อใช้งานถาวร Apple เป็นผู้ประมวลผลการเรียกเก็บเงินและข้อมูลการชำระเงินของ App Store GIFBloom จะไม่ได้รับรายละเอียดบัตรหรือบัญชีชำระเงิน แอปใช้ข้อมูลสิทธิ์การซื้อจาก StoreKit เพื่อให้สิทธิ์เข้าถึงและกู้คืนการซื้อ โดยนโยบายความเป็นส่วนตัวของ Apple มีผลกับการประมวลผลการชำระเงิน"],
  tr: ["Uygulama içi satın alımlar", "GIFBloom, isteğe bağlı olarak otomatik yenilenen haftalık abonelik ve kalıcı erişim sağlayan tek seferlik satın alma sunar. App Store faturalandırma ve ödeme bilgilerini Apple işler. GIFBloom kart veya ödeme hesabı bilgilerinizi almaz. Uygulama, erişim sağlamak ve satın alımları geri yüklemek için StoreKit’in satın alma yetkisi bilgilerini kullanır. Ödeme işlemlerinde Apple’ın gizlilik politikası geçerlidir."],
  vi: ["Mục mua trong ứng dụng", "GIFBloom cung cấp gói đăng ký theo tuần tự động gia hạn không bắt buộc và gói mua một lần để sử dụng vĩnh viễn. Apple xử lý việc tính phí và thông tin thanh toán của App Store. GIFBloom không nhận thông tin thẻ hoặc tài khoản thanh toán. Ứng dụng dùng thông tin quyền mua từ StoreKit để cấp quyền truy cập và khôi phục giao dịch mua. Chính sách quyền riêng tư của Apple áp dụng cho việc xử lý thanh toán."]
};

const order = ["en", "zh-Hans", "zh-Hant", "de", "es", "fr", "it", "ja", "ko", "ru", "pt-BR", "ar", "hi", "id", "th", "tr", "vi"];
const languageLabel = { en: "Language", "zh-Hans": "语言", "zh-Hant": "語言", de: "Sprache", es: "Idioma", fr: "Langue", it: "Lingua", ja: "言語", ko: "언어", ru: "Язык", "pt-BR": "Idioma", ar: "اللغة", hi: "भाषा", id: "Bahasa", th: "ภาษา", tr: "Dil", vi: "Ngôn ngữ" };
const email = "classicalxie@163.com";
const esc = value => String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const page = document.body.dataset.page;

function shell(lang, content) {
  const d = copy[lang];
  const direction = lang === "ar" ? "rtl" : "ltr";
  const suffix = `?lang=${encodeURIComponent(lang)}`;
  const markup = `<header class="topbar"><a class="wordmark" href="index.html${suffix}">GIFBloom</a><nav aria-label="${esc(d.nav[0])}"><a href="index.html${suffix}">${esc(d.nav[0])}</a><a href="support.html${suffix}">${esc(d.nav[1])}</a><a href="privacy-policy.html${suffix}">${esc(d.nav[2])}</a></nav><label class="language-label"><span class="visually-hidden">${esc(languageLabel[lang])}</span><select id="language" aria-label="${esc(languageLabel[lang])}">${order.map(code => `<option value="${esc(code)}"${code === lang ? " selected" : ""}>${esc(copy[code].label)}</option>`).join("")}</select></label></header>${content}<footer><a href="index.html${suffix}">GIFBloom</a><span>© 2026 GIFBloom</span><a href="support.html${suffix}">${esc(d.nav[1])}</a><a href="privacy-policy.html${suffix}">${esc(d.nav[2])}</a><a href="mailto:${email}">${email}</a></footer>`;
  document.documentElement.lang = lang === "zh-Hant" ? "zh-Hant" : lang;
  document.documentElement.dir = direction;
  document.body.innerHTML = shellMarkup(markup);
  document.getElementById("language").addEventListener("change", event => {
    const url = new URL(window.location.href);
    url.searchParams.set("lang", event.target.value);
    window.history.replaceState(null, "", url);
    render(event.target.value);
  });
}

function shellMarkup(inner) {
  return `<div class="site-shell">${inner}</div>`;
}

function featureCards(d) {
  return d.land.slice(3, 9).reduce((cards, value, index, array) => {
    if (index % 2 === 0) cards.push(`<article class="feature"><span class="feature-icon" aria-hidden="true">${["✦", "▧", "♫"][index / 2]}</span><h3>${esc(value)}</h3><p>${esc(array[index + 1])}</p></article>`);
    return cards;
  }, []).join("");
}

function render(lang) {
  const d = copy[lang] || copy.en;
  const nav = d.nav;
  let content = "";
  if (page === "support") {
    const faq = d.support.slice(3, 7).map(([question, answer]) => `<details class="faq"><summary>${esc(question)}</summary><p>${esc(answer)}</p></details>`).join("");
    content = `<main class="content-page"><p class="eyebrow">GIFBloom</p><h1>${esc(d.support[0])}</h1><p class="lede">${esc(d.support[1])}</p><h2>${esc(d.support[2])}</h2><div class="faq-list">${faq}</div><section class="contact-card"><h2>${esc(d.support[7])}</h2><p>${esc(d.support[8])} <a href="mailto:${email}">${email}</a>.</p></section></main>`;
    document.title = `${d.support[0]} — GIFBloom`;
    document.querySelector('meta[name="description"]').content = d.support[1];
  } else if (page === "privacy") {
    const privacySections = d.privacy.slice(1);
    privacySections.splice(privacySections.length - 1, 0, purchasePrivacy[lang]);
    const contactHeading = privacySections[privacySections.length - 1][0];
    const sections = privacySections.map(([heading, body]) => `<section><h2>${esc(heading)}</h2><p>${esc(body)}${heading === contactHeading ? ` <a href="mailto:${email}">${email}</a>.` : ""}</p></section>`).join("");
    const locale = lang === "zh-Hans" ? "zh-CN" : lang === "zh-Hant" ? "zh-TW" : lang === "pt-BR" ? "pt-BR" : lang === "ar" ? "ar-SA" : lang;
    const updated = new Intl.DateTimeFormat(locale, { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" }).format(new Date("2026-09-17T12:00:00Z"));
    const labels = { en: "Last updated", "zh-Hans": "更新日期", "zh-Hant": "更新日期", de: "Zuletzt aktualisiert", es: "Última actualización", fr: "Dernière mise à jour", it: "Ultimo aggiornamento", ja: "最終更新日", ko: "최종 업데이트", ru: "Обновлено", "pt-BR": "Última atualização", ar: "آخر تحديث", hi: "अंतिम अपडेट", id: "Terakhir diperbarui", th: "อัปเดตล่าสุด", tr: "Son güncelleme", vi: "Cập nhật lần cuối" };
    content = `<main class="content-page privacy-page"><p class="eyebrow">GIFBloom</p><h1>${esc(nav[2])}</h1><p class="lede">${esc(d.privacy[0])}</p><p class="updated">${esc(labels[lang])}: ${esc(updated)}</p>${sections}</main>`;
    document.title = `${nav[2]} — GIFBloom`;
    document.querySelector('meta[name="description"]').content = d.privacy[0];
  } else {
    content = `<main><section class="hero"><div class="hero-copy"><p class="eyebrow">${esc(d.land[2])}</p><h1>GIFBloom</h1><p class="tagline">${esc(d.land[0])}</p><p class="lede">${esc(d.land[1])}</p><a class="support-link" href="support.html?lang=${encodeURIComponent(lang)}">${esc(nav[1])} <span aria-hidden="true">→</span></a></div><img class="app-icon" src="appicon.png" alt="GIFBloom app icon"></section><section class="features-section"><p class="eyebrow">GIFBloom</p><h2>${esc(d.land[0])}</h2><div class="feature-grid">${featureCards(d)}</div></section><aside class="privacy-note"><span class="privacy-mark" aria-hidden="true">⌂</span><div><h2>${esc(nav[2])}</h2><p>${esc(d.land[9])}</p></div><a href="privacy-policy.html?lang=${encodeURIComponent(lang)}" aria-label="${esc(nav[2])}">↗</a></aside></main>`;
    document.title = `GIFBloom — ${d.land[0]}`;
    document.querySelector('meta[name="description"]').content = d.land[1];
  }
  shell(lang, content);
}

const supported = new Set(order);
const requested = new URLSearchParams(window.location.search).get("lang");
const preferred = (navigator.languages || [navigator.language || "en"]).map(value => value.toLowerCase());
const traditionalChinese = preferred.some(value => ["zh-tw", "zh-hk", "zh-mo"].some(prefix => value === prefix || value.startsWith(`${prefix}-`)));
const detected = traditionalChinese ? "zh-Hant" : order.find(code => preferred.some(value => value === code.toLowerCase() || value.startsWith(`${code.toLowerCase()}-`))) || (preferred.some(value => value === "zh" || value.startsWith("zh-")) ? "zh-Hans" : preferred.some(value => value === "pt" || value.startsWith("pt-")) ? "pt-BR" : "en");
const initial = requested && supported.has(requested) ? requested : detected;
render(initial);
